CREATE OR REPLACE VIEW V_EDGES_DATA AS

WITH latest_deps AS (SELECT MAX(RUN_ID) AS RUN_ID FROM SIGMA_DATASET_DEPENDENCIES)

SELECT DISTINCT
    PARENT_ID  AS source,
    DATASET_ID AS target,
    'ds-ds'    AS edge_type
FROM SIGMA_DATASET_DEPENDENCIES
WHERE PARENT_ID IS NOT NULL
  AND RUN_ID = (SELECT RUN_ID FROM latest_deps)

UNION ALL

SELECT DISTINCT
    d.DATASET_ID  AS source,
    w.WORKBOOK_ID AS target,
    'ds-wb'       AS edge_type
FROM SIGMA_WORKBOOK_SOURCE_DETAILS w
JOIN SIGMA_DATASET_DEPENDENCIES d ON w.DATASET_ID = d.DATASET_ID
WHERE w.DATASET_ID IS NOT NULL
  AND d.RUN_ID = (SELECT RUN_ID FROM latest_deps);
